version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10. # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build

jobs:
  build:
    steps:
      - run: npm install
      - run: npm start
